# Generated by Django 4.2 on 2023-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
    ]
