# Generated by Django 4.2 on 2023-06-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_ud',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
